### ISSUE TITLE
Cannot upload file in Drupal

### ISSUE THREAD

**Issue by msound** [NBCUTechnology/pubstack#141]
Because of the way NFS is mounted in Vagrant, the PHP `is_writable()` function returns `FALSE` in Drupal (includes/file.inc line 446). This problem is reported in many places. Consider passing mounting options in VagrantFile.

**Comment by IvoPereira** [comment]
@scottrigby you were always to get it to work like that?

I've been facing this issue every time I've been creating a new machine in OSX, and it looks like that doesn't solve it for me unfortunately.

**Comment by scottrigby** [comment]
@IvoPereira Yes it has always worked for me when I do it ahead of time like this. 

So I could have sworn I had this in the README, but i checked history and it's not there. Here's what you need to do before you install Publisher within your VM:

Make sure when you do it (`chmod -R a+w sites/X/files`), you do that on vagrant'
s concept of the "host machine" (in this case your Mac), not from within the VM itself (they call this the "guest machine"). Although it's annoying, this is actually considered a feature not a bug - because your Vagrant user shouldn't have access to change permissions for directories on your host machine like that. Can you see if that works for you?

**Comment by rabellamy** [comment]
See #194
